<a href="https://colab.research.google.com/github/fariya09ahmed-commits/Fariya-Ahmed/blob/master/assg_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

# Import necessary library
import pandas as pd
import numpy as np

#assg-1
range_array=np.arange(1,100,20)
print("Range array:", range_array)
total_sum=np.sum(range_array)
print(total_sum)

Range array: [ 1 21 41 61 81]
205


In [ ]:
#assg-2
arr=np.array([10,20,30,40,50,60])
maximum_value=np.max(arr)
minimum_value=np.min(arr)
print("Maximum value:" ,maximum_value)
print("Minimum value:", minimum_value)

Maximum value: 60
Minimum value: 10


In [ ]:
#assg-3
arr1=np.arange(1,100,20)
arr2=np.arange(100,200,20)
result= arr1 * arr2
print(arr1)
print(arr2)
print(result)

[ 1 21 41 61 81]
[100 120 140 160 180]
[  100  2520  5740  9760 14580]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd   # <-- You forgot this import

file_path = '/content/drive/MyDrive/python dataset/Ass-3 data.xlsx'
columns = ["A", "B", "C"]

df = pd.read_excel(file_path, names=columns)
print("Dataset loaded successfully. Shape:", df.shape)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Dataset loaded successfully. Shape: (5, 3)


In [ ]:
#assg-1
print(df.head())
print("\nDataset info:")
print(df.info())
print("\nDescriptive statistics:")
print(df.describe())

     A    B    C
0   12   20   15
1   45   40   49
2  120   80  150
3   60   55   90
4  150  120  160

Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes
None

Descriptive statistics:
                A          B           C
count    5.000000    5.00000    5.000000
mean    77.400000   63.00000   92.800000
std     56.380848   38.66523   62.782959
min     12.000000   20.00000   15.000000
25%     45.000000   40.00000   49.000000
50%     60.000000   55.00000   90.000000
75%    120.000000   80.00000  150.000000
max    150.000000  120.00000  160.000000


In [ ]:
#assg-2
print("\nSum of each column:")
print(df.sum())


Sum of each column:
A    387
B    315
C    464
dtype: int64


In [ ]:
#assg-3
print("\nMean of each column:")
print(df.mean())


Mean of each column:
A    77.4
B    63.0
C    92.8
dtype: float64
